[project]
name = "group-ai-plan-thingy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "django>=5.2.8",
    "django-environ>=0.12.0",
    "psycopg>=3.2.13",
]
